repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      # Lint + autofix (includes isort via rule "I")
      - id: ruff
        args: [--config=pyproject.toml, --fix]

      # Formatter (Black-like)
      - id: ruff-format
        args: [--config=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          [
            types-requests,
            types-PyYAML,
            types-setuptools,
            types-python-dateutil,
            "pydantic[mypy]==2.11.7",
            types-toml,
          ]
        args: [--config-file=pyproject.toml]
